name: release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Build
        run: bash release.sh

      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "beta"
          draft	: true
          files: output/ukita_installer.exe
